version: '3.8'


services:
  devContainer:
    container_name: devContainer
    command: tail -f /dev/null
    image: node:lts
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 3001:3001